# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compress-dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 150)
        Dialog.setMinimumSize(QtCore.QSize(300, 150))
        Dialog.setMaximumSize(QtCore.QSize(300, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_rotate1 = QtWidgets.QRadioButton(Dialog)
        self.btn_rotate1.setObjectName("btn_rotate1")
        self.horizontalLayout_2.addWidget(self.btn_rotate1)
        self.btn_rotate2 = QtWidgets.QRadioButton(Dialog)
        self.btn_rotate2.setObjectName("btn_rotate2")
        self.horizontalLayout_2.addWidget(self.btn_rotate2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setMaximumSize(QtCore.QSize(120, 40))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_3.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_rotate1.setText(_translate("Dialog", "Horizontal Mirror"))
        self.btn_rotate2.setText(_translate("Dialog", "Vertical Mirror"))
        self.btn_save.setText(_translate("Dialog", "Save Change"))
